### ISSUE TITLE
New feature: Opportunity for code reuse in single qubit gates

### ISSUE THREAD

**Issue by aniabrown** [QuEST-Kit/QuEST#110]
There are a number of single qubit gates which follow the same pattern of updating pairs of elements in the state vector using the value of those two elements. It is possible to replace these with a single function that masks out the values that don't need to be used in each particular case for specific gates. Investigate if this removes enough code to be worth the added layer of abstraction

**Comment by TysonRayJones** [comment]
All algorithmic code duplication eradicated in v4! 🎉
