### ISSUE TITLE
Bug: build system include directories problem with cmake 3.5.1 and cuda

### ISSUE THREAD

**Issue by aniabrown** [QuEST-Kit/QuEST#129]
Using cmake 3.5.1 and GPUACCELERATED=true, there is a bug where a library added with cuda_add_library won't pick up the include files in target_include_directories. See -- https://gitlab.kitware.com/cmake/cmake/issues/16571

This was patched and does work using cmake 3.10.2. I haven't tested earlier versions of cmake. 

Possible solutions are either to use include_directories rather than target_include_directories (bad practice) or to increase the cmake minimum required version

**Comment by chr5tphr** [comment]
Looking at the bug report and the resulting [commit](https://gitlab.kitware.com/cmake/cmake/-/commit/7ded655f7ba82ea72a82d0555449f2df5ef38594) this seems to have been fixed earliest in version 3.7.
CMake 3.7.0 is at this point 3 years old, so it should be reasonable to increase the required cmake version.

I created a pull request at #261

**Comment by TysonRayJones** [comment]
Well spotted, cheers!
