### ISSUE TITLE
Bug: 2qubit Kraus Map

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#162]
The Kraus map {{1,0,0,0},{0,0,1,0},{0,1,0,0},{0,0,0,1}} (i.e. the SWAP matrix) is passing validation but breaks density matrix normalisation, such that the probabilities of qubit measurement outcomes are wrong (e.g. 2.3)

(This is at least occurring in QuEST-MMA which wraps twoQubitKrausMap - I can make a MWE later)

**Comment by TysonRayJones** [comment]
MWE:

```C++
#include <stdio.h>
#include "QuEST.h"

int main (int narg, char *varg[]) {

    QuESTEnv env = createQuESTEnv();
    Qureg qureg = createDensityQureg(2, env);
    initPlusState(qureg);
    
    // apply kraus = swap
    ComplexMatrix4 matr = {0};
    matr.r0c0.real=1;
    matr.r1c2.real=1;
    matr.r2c1.real=1;
    matr.r3c3.real=1;
    applyTwoQubitKrausMap(qureg, 0, 1, (ComplexMatrix4[]) {matr}, 1);
    
    printf("total prob: %g\n", calcTotalProb(qureg));

    destroyQureg(qureg, env); 
    destroyQuESTEnv(env);
    return 0;
}
```

outputs:
```bash
total prob: 15
```
(instead of the before-Kraus prob of `1`).

**Comment by BalintKoczor** [comment]
Fixed this bug in 2e705850db59741565f9a4c98a2da65dc1bee818.
It is quite tedious to manipulate ComplexMatrixN and the other matrix
structs currently. The ComplexMatrixN superoperator was previously initialised
as:
```
// initialise to zero matrix
    Complex* matr[superOp.numRows];
    for (int r=0; r < superOp.numRows; r++) {
        Complex row[superOp.numRows];
        for (int c=0; c < superOp.numRows; c++)
            row[c] = (Complex) {.real=0, .imag=0};
        matr[r] = row;
    }
    superOp.elems = matr;
```

Replacing it with 
```
  superOp.elems = (Complex **) malloc(sizeof(Complex *) * superOp.numRows);;
    for (int r=0; r < superOp.numRows; r++) {
        superOp.elems[r] = calloc(superOp.numRows, sizeof(Complex));
    }
```
solved the issue.

This issue relates to #161 as well.

**Comment by TysonRayJones** [comment]
This was intentional to avoid having to call `malloc` during the call. Are you sure it is not possible to attach an array (in the stack, not malloc'd in the heap) to the struct here to pass on?
 I think I'd like to work out whether this is possible before conceding to `malloc`. I'd probably opt to refactor to avoid it

**Comment by TysonRayJones** [comment]
(also note of course this patched introduced a memory leak; the superOp needs to be freed)

**Comment by TysonRayJones** [comment]
Got a stack-based method (no `malloc`) working in 42b2de0f42c650e9e56dcf150ffcd6ea76b8ca55
