### ISSUE TITLE
Finite measurement and Pauli operators 

### ISSUE THREAD

**Issue by rugantio** [QuEST-Kit/QuEST#178]
Hello,
I'm trying to retrieve the expected value of a tensored Pauli operator on a statevec, for example <ψ|ZZ|ψ>. I found out that there's a function in the dev branch calcExpecPauliProd (thx a lot!!), but it's actually computed using the inner product, according to the header file. It would be interesting to estimate the value from (a finite number of) measurements, similarly to a real quantum computer.

Finite measurement can be performed easily on a single qubit, for example, if p0 and p1 are variables that are to store the respective probabilities of |0> and |1>: 

```
void finiteMeasure(Qureg qureg, QuESTEnv env, int measureQubit, qreal *p0, qreal *p1, int iterations){
    int occ0 = 0, occ1 = 0;
    double f0,f1; 
    for(int i = 0; i < iterations; i++){
        Qureg qureg_clone = createQureg(qureg.numQubitsRepresented, env);
        cloneQureg(qureg_clone,qureg);          
        int outcome = measure(qureg_clone, measureQubit);
        if (outcome == 0)
            occ0++;
        else
            occ1++;
    }
    f0 = (double)occ0 / iterations;
    f1 = (double)occ1 / iterations;
    *p0 = f0;
    *p1 = f1;     
}
```
For a single qubit the expValue <ψ|Z|ψ> is simply p0-p1, as explained [here](https://dkopczyk.quantee.co.uk/vqe/). However when multiple qubits are to be measured, it is not so simple, ["One additional note, while it may be tempting to assume that measuring Z⊗Z is the same as measuring Z⊗1 and then 1⊗Z, this assumption would be false."](https://docs.microsoft.com/en-us/quantum/concepts/pauli-measurements?view=qsharp-preview) and so, if I understand correctly, we need a routine to measure more than one qubit at the same time, [to get the expValue](https://quantumcomputing.stackexchange.com/questions/7055/expected-value-of-a-product-of-the-pauli-matrices-in-different-bases). Is this feasible?

**Comment by rugantio** [comment]
Ok I think I got something here... It seems that I can actually use single qubit measures to retrieve the expValue. I'll try to introduc you to my code, maybe it could also be useful for issue #171  
So, since I didn't know that you guys were working on this I had made my own Hamiltonian struct as a linked list, each item of the list holds a tensored pauli operator in this format:
```
typedef struct Hamiltonian{ 
    qreal coefficient; //real coefficient of the tensored Pauli
    char* pauli_string; //op in the form ZXZ... without identities 
    int* qubs;          //indices of qubits where the op acts 
    int n_pauli;        //length of the op
    double expval;      //placeholder for an expval of the op 
    struct Hamiltonian* next;
} Hamiltonian;
```
the list is populated recursively using recursive functions such as:
```
Hamiltonian* newPauliOp(qreal coefficient, char* pauli_string, int* qubs, int n_pauli){
/*create the PauliOp nodes that store the qubit Hamiltonian*/
    Hamiltonian* new_pauli_op = malloc(sizeof(Hamiltonian)); 
    new_pauli_op->coefficient = coefficient; 
    new_pauli_op->pauli_string = pauli_string; 
    new_pauli_op->qubs = qubs;
    new_pauli_op->n_pauli = n_pauli;
    new_pauli_op->next = NULL;
    return new_pauli_op; 
} 
Hamiltonian* insertPauliOp(Hamiltonian* hamiltonian, qreal coefficient, char* pauli_string, int* qubs, int n_pauli){ 
/*constructor of the Hamiltonian struct*/
    if(hamiltonian == NULL) {    //create first node
        return newPauliOp(coefficient, pauli_string, qubs, n_pauli); 
    }
    //traverse the list
    else 
     hamiltonian->next = insertPauliOp(hamiltonian->next, coefficient, pauli_string, qubs, n_pauli); 
    return hamiltonian; 
} 
```
The Hamiltonian is evaluated with the function:
```
qreal evaluateHamiltonian(Hamiltonian* hamiltonian, Qureg qureg, QuESTEnv env, double finalexp){
        if (hamiltonian == NULL)
        return finalexp; 
    Qureg qureg_clone = createQureg(qureg.numQubitsRepresented, env);
    cloneQureg(qureg_clone, qureg);       
    double expval = evaluateMultiPauli(qureg_clone, hamiltonian->pauli_string, hamiltonian->qubs, hamiltonian->coefficient);
    // printf("coeff: %f\t",hamiltonian->coefficient);
    // printf("pauli_string: %s\n",hamiltonian->pauli_string);
    // printf("expval: %f\n",expval);
    hamiltonian->expval = expval;
    finalexp += expval;
    // printf("finalexp: %f\n\n",finalexp);
    evaluateHamiltonian(hamiltonian->next, qureg, env, finalexp);
}
```
where evaluateMultiPauli is defined as:
```
qreal evaluateMultiPauli(Qureg qureg, char paulis[], int qubs[], double coeff){
    double prod = 1;
    for(int i = 0; paulis[i] != '\0'; i++){
        switch(paulis[i]){
            case 'X':
                pauliX(qureg,qubs[i]);
                hadamard(qureg,qubs[i]);
                break;
            case 'Y':
                pauliY(qureg,qubs[i]);
                rotateX(qureg,qubs[i],-M_PI/2);
                break;     
            case 'Z':
                pauliZ(qureg,qubs[i]);
                break;     
        }
        prod *= evaluatePauli(qureg,qubs[i]);
    }
    return prod*coeff;
}
```
and evaluatePauli can be implemented using finite measurement introduced in my previous post.
The results that I get using this pipeline are the same as calcExpecPauliSum but it seems that they are a lot faster to compute! Here's a benchmark using the H2 molecule, on 4 qubits, where expected values are evaluated on all the possible basis states (Slater determinants) and printed one after the other. In this case finite sampling is not used, I just used measureWithStats to make the comparison more plausible.
```
pauli_string: , qubs: []        coeff: -0.10649450305549127     n_pauli: 0
pauli_string: XZX,      qubs: [0, 1, 2, ]       coeff: 0.04539409415989076      n_pauli: 3
pauli_string: XZXZ,     qubs: [0, 1, 2, 3, ]    coeff: 0.04539409415989076      n_pauli: 4
pauli_string: YZY,      qubs: [0, 1, 2, ]       coeff: 0.04539409415989076      n_pauli: 3
pauli_string: YZYZ,     qubs: [0, 1, 2, 3, ]    coeff: 0.04539409415989076      n_pauli: 4
pauli_string: Z,        qubs: [0, ]     coeff: 0.17308580606009916      n_pauli: 1
pauli_string: ZZ,       qubs: [0, 1, ]  coeff: 0.17308580606009918      n_pauli: 2
pauli_string: ZZZ,      qubs: [0, 1, 2, ]       coeff: 0.16603496547554686      n_pauli: 3
pauli_string: ZZZZ,     qubs: [0, 1, 2, 3, ]    coeff: 0.16603496547554686      n_pauli: 4
pauli_string: ZZ,       qubs: [0, 2, ]  coeff: 0.12064087131565607      n_pauli: 2
pauli_string: ZZZ,      qubs: [0, 2, 3, ]       coeff: 0.12064087131565607      n_pauli: 3
pauli_string: Z,        qubs: [1, ]     coeff: 0.16860783437404908      n_pauli: 1
pauli_string: ZZZ,      qubs: [1, 2, 3, ]       coeff: -0.22131245056804433     n_pauli: 3
pauli_string: ZZ,       qubs: [1, 3, ]  coeff: 0.17474227780254478      n_pauli: 2
pauli_string: Z,        qubs: [2, ]     coeff: -0.22131245056804433     n_pauli: 1
-------------------------------------------------------
Initializing QuEST
-------------------------------------------------------
0)exp_val: 0.713754
1)exp_val: -1.125293
2)exp_val: -0.540633
3)exp_val: -0.359056
4)exp_val: 0.452300
5)exp_val: 0.906661
6)exp_val: -0.359056
7)exp_val: -0.540633
8)exp_val: 0.233543
9)exp_val: -0.458801
10)exp_val: -0.542985
11)exp_val: -0.542985
12)exp_val: 0.233543
13)exp_val: -0.458801
14)exp_val: 0.342265
15)exp_val: 0.342265
Time to solution with calcExpecPauliSum: 2.755575
0) final_exp: 0.713754
1) final_exp: -1.125293
2) final_exp: -0.540633
3) final_exp: -0.359056
4) final_exp: 0.452300
5) final_exp: 0.906661
6) final_exp: -0.359056
7) final_exp: -0.540633
8) final_exp: 0.233543
9) final_exp: -0.458801
10) final_exp: -0.542985
11) final_exp: -0.542985
12) final_exp: 0.233543
13) final_exp: -0.458801
14) final_exp: 0.342265
15) final_exp: 0.342265
Time to solution with evaluateHamiltonian: 0.020697
``` 
Let me know what you think of it!

**Comment by rugantio** [comment]
Oops I placed the timing functions in the wrong place, calcExpecPauliSum is actually quite a bit faster. Do you have any idea on how to improve evaluateHamiltonian? 
I tested it again on LiH, 12 qubits on a quadcore i7-7500U 16GB RAM machine, with all 4096 amplitudes:
```
Time to solution with calcExpecPauliSum: 542.365135
Time to solution with evaluateHamiltonian: 2139.586518
```
Also I forgot to include `destroyQureg(qureg_clone, env);` at the end of evaluateHamiltonian.
If you have a better (faster) solution to estimate the finite sampling let me know!

**Comment by TysonRayJones** [comment]
Hi Rugantio,

Thanks for your interest in QuEST! I am a little confused by your request though. 

`calcExpecPauliProd` returns the expected value at "full" numerical precision; there is hence no need to approximate it with Monte Carlo sampling. If you want to simulate shot noise in a measurement of the expected value, then you can simply do so by generating a random variable with expected value that returned by `calcExpecPauliProd`. I do so in the [supplementary material ](https://static-content.springer.com/esm/art%3A10.1038%2Fs41534-019-0187-2/MediaObjects/41534_2019_187_MOESM1_ESM.pdf) (**B. Lithium Hydride >> 2. Numerical simulation**) of [this paper](https://www.nature.com/articles/s41534-019-0187-2).

There seems little point in repeatedly calling `measure` when you already know the distribution; it's an inefficient way to "get the expected value inaccurately" ;)

**Comment by rugantio** [comment]
Hey Tyson, thank you for this great tool!
My idea was to bluntly imitate what a quantum computer does, but what you're saying is actually much more efficient. So basically I only need to shift the calcExpecPauliProd by my total error:
newExpecPauliProd = ((1-gate_err)^depth_of_circuit)*oldExpecPauliProd
and if I had different gate_err for 1 and 2 qubit gates I guess I can compose the total error as
((1-gate_err_1Q)^depth_of_1Q)*((1-gate_err_2Q)^depth_of_2Q)
Is this sound?

**Comment by TysonRayJones** [comment]
Hmm that's an (admittedly, quite crude) approximation of how errors in the gates accrue error in the expected value. We're reasoning that our circuit is sufficiently big and the errors "uniformly random" that they shift us directly to the fully mixed state. Your calculation is sound if you believe those assumptions are still maintained. Note this gate error is a very different error due to that by finite-sampling of the expected value from perfect gates, as you first ask about.

If you want to reliably understand how gate errors affect your expected value, you should switch over to a density-matrix simulation. There's doc for the dev branch hosted [here](https://github.com/QuEST-Kit/QuEST-develop-doc) - obviously use dev at your own risk!
```C++
Qureg qureg = createDensityMatrix(10)
```
After you apply a gate, you can also induce an error channel on your qubits (see the list of supported errors [here](https://quest-kit.github.io/QuEST-develop-doc/group__decoherence.html)). 
The result of `calcExpecPauliProd` will then be shifted due to those errors. If you additionally want shot noise (due to finite sampling of this expected value, like an experimentalist faces), plug the result into a RNG as above.

**Comment by rugantio** [comment]
Thank you so much for your help, I'll try to use the density matrix approach and see what to make of it. I can close the issue :)
