### ISSUE TITLE
Develop not building with OpenMP support

### ISSUE THREAD

**Issue by nfwvogt** [QuEST-Kit/QuEST#197]
Gcc  throws a compile error for me when building with OpenMP support after commit f8c0e7f

`gcc -x c -O2 -std=c99 -mavx -Wall -DQuEST_PREC=2 -fopenmp -fpic -I
../../QuEST/QuEST/src/../include -I ../../QuEST/QuEST/src/CPU -I../../QuEST/QuEST/src -c 
../../QuEST/QuEST/src/CPU/QuEST_cpu.c ../../QuEST/QuEST/src/CPU/QuEST_cpu.c: In function ‘statevec_multiControlledMultiQubitUnitaryLocal’: 
../../QuEST/QuEST/src/CPU/QuEST_cpu.c:1856:62: error: ‘g’ undeclared (first use in this function) private (thisTask,thisInd00,thisGlobalInd00,ind,i,t,r,c,g,reElem,imElem, ampInds,reAmps,imAmps) ^ 
../../QuEST/QuEST/src/CPU/QuEST_cpu.c:1856:62: note: each undeclared identifier is reported only once for each function it appears in`

(I also commented on the commit itself but later realised that github doesn't send notifications for commit comments by default)

**Comment by TysonRayJones** [comment]
That's a leftover OpenMP var `g` from [this patch](https://github.com/QuEST-Kit/QuEST/commit/62cdd38d41505e6a3752216cb2830dda24cc93c5). Patched with two backspaces. Cheers!
