### ISSUE TITLE
 Could not allocate memory on GPU!

### ISSUE THREAD

**Issue by zhaoxiongjun** [QuEST-Kit/QuEST#209]
Use GPU acceleration according to the tutorial, but after running ./demo, an error occurs ：“memory cannot be allocated on the GPU” . Why？ How can i solve it.
按照教程的方式使用GPU加速，但是运行./demo后出现报错，无法分配内存在GPU

**Comment by TysonRayJones** [comment]
That error is triggered when `cudaMalloc` fails (see [here](https://github.com/QuEST-Kit/QuEST/blob/master/QuEST/src/GPU/QuEST_gpu.cu#L306)), which usually implies that the attempted state-vector (created with `createQureg`) was too large to fit in GPU memory.
I imagine though your GPU can fit the 64 bytes needed for the tutorial's 3-qubit register :)

I would guess you've supplied the wrong `GPU_COMPUTE_CAPABILITY` for your GPU. Look up your GPU [here](https://developer.nvidia.com/cuda-gpus), and as per the [tutorial](https://github.com/QuEST-Kit/QuEST/blob/master/examples/README.md#compiling), compile with
```bash
cmake -DGPUACCELERATED=1 -DGPU_COMPUTE_CAPABILITY=[COMPUTE_CAPABILITY] ..
```

**Comment by zhaoxiongjun** [comment]
thanks, i will try it. and my GPU is Tesla P100------------------ 原始邮件 ------------------
发件人: "Tyson Jones"<notifications@github.com>
发送时间: 2020年1月15日(星期三) 晚上7:00
收件人: "QuEST-Kit/QuEST"<QuEST@noreply.github.com>;
抄送: "伊口赵"<2540685662@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [QuEST-Kit/QuEST]  Could not allocate memory on GPU! (#209)



That error is triggered when cudaMalloc fails (see here), which usually implies that the attempted state-vector (created with createQureg) was too large to fit in GPU memory.
 I imagine though your GPU can fit the 64 bytes needed for the tutorial's 3-qubit register :)
 
I would guess you've supplied the wrong GPU_COMPUTE_CAPABILITY for your GPU. Look up your GPU here, and as per the tutorial, compile with
 cmake -DGPUACCELERATED=1 -DGPU_COMPUTE_CAPABILITY=[COMPUTE_CAPABILITY] ..
 
&mdash;

**Comment by TysonRayJones** [comment]
How'd you get on with this? Did a different `GPU_COMPUTE_CAPABILITY` fix your issue?

**Comment by zhaoxiongjun** [comment]
> How'd you get on with this? Did a different `GPU_COMPUTE_CAPABILITY` fix your issue?

no，I got a bigger memory GPU

**Comment by TysonRayJones** [comment]
Are you saying you switched to a different GPU which incidentally has QuEST's default `GPU_COMPUTE_CAPABILITY = 30`? The tutorial example requires a negligible amount of GPU memory (as said, 64 bytes).

**Comment by zhaoxiongjun** [comment]
> Are you saying you switched to a different GPU which incidentally has QuEST's default `GPU_COMPUTE_CAPABILITY = 30`? The tutorial example requires a negligible amount of GPU memory (as said, 64 bytes).

I think the error reason is my program needs more GPU memory, bacause when I run my program at a 32G GPU, no this error!

**Comment by TysonRayJones** [comment]
Ah I thought you were referring to the previously mentioned tutorial, which definitely does not demand 32 GiB. Sounds like a simple hardware problem then :)
