### ISSUE TITLE
Run a simple code use GPU, but got a error answer

### ISSUE THREAD

**Issue by zhaoxiongjun** [QuEST-Kit/QuEST#221]
```
// init and prepare
    Qureg q = createQureg(1, Env);
    initZeroState(q);
    float q_measure[10];

    // apply circuit
    hadamard(q, 0);
    
    // output probs
    for(long long int i=0; i<1; ++i){
        q_measure[i] = calcProbOfOutcome(q,  i, 1);
        fprintf(fp, "Probability for q[%2lld]==1 : %lf    \n", i, q_measure[i]);
    }
```
The right output is 0.5, but got 1.0 when run at GPU. And run this code at CPU can get right answer. WHY ? ? ?

**Comment by TysonRayJones** [comment]
Hi,

As per your other issue (#209), are you setting the correct compute-capability for your GPU? To check you're setting it correctly, you should run the unit tests on the [develop](https://github.com/QuEST-Kit/QuEST/tree/develop) branch, via (replacing `[here]` with your GPU's compute capability, without decimal points):

```bash
mkdir build && cd build
cmake .. -DTESTING=ON -DGPU_COMPUTE_CAPABILITY=[here]
make
./tests/tests exclude:mixMultiQubitKrausMap -c "correctness"
```
There, I run only the correctness checks (not input validation checks) and exclude the slowest test. These tests will fail if you do not set `GPU_COMPUTE_CAPABILITY` correctly.

________

Finally, the QuEST API provides a precision-agnostic `qreal` type, which will resolve to `float`, `double` or `long double` depending on your compile-time configuration. Hence, I suggest you to avoid using `float` (which is *not* the default precision), and use `qreal` instead. That is, change
```C
float q_measure[10];
```
to
```C
qreal q_measure[10];
```

Let me know how you get on!

**Comment by zhaoxiongjun** [comment]
Thanks very much. I have run the unit test according to the command you provided. and all tests passed（My GPU is P100, the GPU_COMPUTE_CAPABILITY is set to 60).

**Comment by zhaoxiongjun** [comment]
.

**Comment by TysonRayJones** [comment]
Excellent, does this correct your issue (changing also `float` to `qreal`)?

**Comment by zhaoxiongjun** [comment]
Unfortunately，still get 1.0 when running on GPU. But run another program as follows, can get right answers.
```
// init and prepare
    Qureg q = createQureg(1, Env);
    initZeroState(q);
    qreal  q_measure[10];

    // apply circuit
    hadamard(q, 0);
    
    // output probs
    for(long long int i=0; i<1; ++i){
        q_measure[i] = calcProbOfOutcome(q,  i, 1);
        fprintf(fp, "Probability for q[%2lld]==1 : %lf    \n", i, q_measure[i]);
    }
```
Very strange. Maybe I need to know how QuEST works when using GPU

**Comment by TysonRayJones** [comment]
Is that precisely the correction I just twice nominated? In C, you shouldn't cast doubles (the default qreal) to lower precision (float). In QuEST, for precision agnosticism, use qreal
