### ISSUE TITLE
Use GPU to compile QuEST

### ISSUE THREAD

**Issue by EventHorizonElliot** [QuEST-Kit/QuEST#224]
Hi TysonRayJones

Whether to call only one GPU during compiling by default? Our project requires more than 16G VRAM and the GPU we used is Tesla P100, which has only 16G per card. When we try to compile the program, the following error will appear:
`Could not allocate memory on GPU!`
Would you please tell me how to call  two or more GPUs simultaneously?  Well, if it is not possible, could we load the program into RAM but compute it on GPU? 

We will be very glad if we get your reply! 
Thank you very much!

**Comment by TysonRayJones** [comment]
Hi EventHorizonElliot,

QuEST does not have native support for multiGPU. Splitting simulation between RAM and VRAM is also not possible, and would induce an incredible slowdown per gate due to the memory movement
