### ISSUE TITLE
MULTI-GPU Version

### ISSUE THREAD

**Issue by zhangliang1997** [QuEST-Kit/QuEST#226]
Hi QuEST team :)
I'm a student majoring in the architecture of GPU and  i have written a original version of multi-node && multi-GPU. I have some questions and i did't find email address to send email. So i come here and want to get a email address to  ask some questions:)
my email:418761644@qq.com

**Comment by zhangliang1997** [comment]
my email address is 418761644@qq.com

**Comment by TysonRayJones** [comment]
Hi there, 
Our email address is plainly stated in the **Contact** section of the README, as `quest@materials.ox.ac.uk`. However, we've been getting many questions about multi-GPU, so would prefer you ask your questions in this Github issue, to reduce duplication.

**Comment by zhangliang1997** [comment]
got it

**Comment by zhangliang1997** [comment]
got it
