### ISSUE TITLE
gethostname still implicitly declared in some compilers

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#23]

**Comment by TysonRayJones** [comment]
Fixed

**Comment by TysonRayJones** [comment]
This is still a warning with some MPI compilers

**Comment by TysonRayJones** [comment]
See commit 3db5566 (ineffectual fix)

**Comment by aniabrown** [comment]
Addresses in pull request #132. Removed hostname seeding completely. This should be noted in future release notes.
