### ISSUE TITLE
Compile failure with gcc >= 9

### ISSUE THREAD

**Issue by we-taper** [QuEST-Kit/QuEST#234]
Could you please update the README file with a notice about the gcc version requirement?

I had recently failed to compile QuEST with gcc, only to realize that I needed to downgrade my gcc version from 9 to 8. (9 is now the default with ubuntu >= 19.10).

**Comment by TysonRayJones** [comment]
Hi Hongxiang,

`gcc-9` (9.3.0) compiles fine for me on MacOS, so you'll have to give me more info (e.g. build log). While I appreciate your frustration, no, providing a list of all compatible compilers and versions is impractical. In any case, we try to make QuEST's compatibility as wide as possible.

You've possibly been bit by a change in syntax of gcc-9's default OpenMP version 5.0 (I assume you were compiling with `MULTITHREADED=1`). Though not documented (though I may misremember), variables not explicitly denoted in the OpenMP pragma are no longer assumed _shared_. We'll have to update QuEST's multithreading code to correct this. You'll appreciate this is a game of cat-and-mouse with new compilers.

**Comment by we-taper** [comment]
Thank Tyson.
Yes I agree that providing the exact specification would be difficult.
I think you are right as the error message I had (attached) is related to
```c
# pragma omp parallel
```
I will give it another try by tweaking the `MULTITHREADED` variable later.
[Dockererror.txt](https://github.com/QuEST-Kit/QuEST/files/4339326/Dockererror.txt)

**Comment by TysonRayJones** [comment]
Setting
```
MULTITHREADED=0
``` 
will definitely allow gcc-9 to compile. I'll close this issue, since the culprit is #235
