### ISSUE TITLE
Add support for OpenMP 5.0

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#235]
which is the default version in `gcc-9`. This requires updating the OpenMP pragmas to explicitly specify all (formerly, assumed) shared variables.

**Comment by zv-io** [comment]
In order to maintain compatibility with OpenMP 4.0, the `firstprivate` clause is used instead of adding these variables to the existing `shared` clauses.

**Comment by TysonRayJones** [comment]
patched in ec9871bd57fe8c859bd68a1a5c284b2b7e9ffee7
