### ISSUE TITLE
statevec_destroyQureg didn't free the memory.

### ISSUE THREAD

**Issue by harry900831** [QuEST-Kit/QuEST#239]
In the GPU version, the funtion [statevec_destroyQureg](https://github.com/QuEST-Kit/QuEST/blob/master/QuEST/src/GPU/QuEST_gpu.cu) seems that won't free the memory of **qureg->firstLevelReduction** and **qureg->secondLevelReduction**.

**Comment by TysonRayJones** [comment]
Hi Harry,

Well spotted! We've patched this in our latest release ([v3.1.1](https://github.com/QuEST-Kit/QuEST/releases/tag/v3.1.1)).
Cheers!
