### ISSUE TITLE
Missing a file named “QuEST_generated_QuEST_gpu.cu.o.cmake.pre-gen” comparing normal project in another machine after cmake.

### ISSUE THREAD

**Issue by pengber** [QuEST-Kit/QuEST#241]
I want run project using GPU,but after
`cmake -DCMAKE_C_FLAGS=-std=c99 -DMULTITHREADED=OFF -DDISTRIBUTED=OFF -DGPUACCELERATED=ON -DGPU_COMPUTE_CAPABILITY=70 ..`
`make`
it shows 
![image](https://user-images.githubusercontent.com/58100402/77299989-4dd2c700-6d28-11ea-8fed-c7c8829c9e3a.png)
then I compared the content of  QuEST/CMakeFiles/QuEST.dir/src/GPU/ with a normal project in my another machine, I find this one lack a file named "QuEST_generated_QuEST_gpu.cu.o.cmake.pre-gen" comparing the normal one after cmake.

I don't konw whether I did some steps wrong, if someone met this problem too and solved it, please help me, thank you.

**Comment by TysonRayJones** [comment]
Hi, 
Apologies for the delay!

The error about the missing missing "generated" files are just a result of compiling failing due to your first error, that is
```bash
QuEST_gpu: fatal error: QuEST.h: No such file or directory
```
Your build commands work fine on my system (gcc 6.5, nvcc 9.1).
Can you please tell me your compiler and cmake versions (or just show me the full output of your commands)?

Does the following work (you can paste the whole thing in to terminal):
```bash
cd ~/Downloads
git clone https://github.com/QuEST-Kit/QuEST.git
cd QuEST

mkdir build
cd build

cmake -DCMAKE_C_FLAGS=-std=c99 -DMULTITHREADED=OFF -DDISTRIBUTED=OFF -DGPUACCELERATED=ON -DGPU_COMPUTE_CAPABILITY=70 ..
make
./demo
```

**Comment by pengber** [comment]
> ssing missing "generated" files are just a result of compiling failing due to your first error, that is

Hi!
Very thanks for your reply!
gcc  version 5.4.0,cmake version 3.5.1
I user you commands in the machine,and there is still something wrong:
![图片](https://user-images.githubusercontent.com/58100402/78795628-cbb0f680-79e7-11ea-8f06-43175411a971.png)

**Comment by TysonRayJones** [comment]
Hi,
Without seeing your full CMake output, I can only speculate at the problem.
Are you able to compile using the example makefile directly?

In the root folder for QuEST (the directory within which you'll see the `examples` direc), try:
```bash
cp examples/makefile .
make GPUACCELERATED=1 GPU_COMPUTE_CAPABILITY=70 EXE=myapp SOURCES='<name>'
```
where <name> is a space-separated list of your source files (without file extensions).

If successful, this will make a `myapp` executable. Does this work?

**Comment by pengber** [comment]
> 
> 
> Hi,
> Without seeing your full CMake output, I can only speculate at the problem.
> Are you able to compile using the example makefile directly?
> 
> In the root folder for QuEST (the directory within which you'll see the `examples` direc), try:
> 
> ```shell
> cp examples/makefile .
> make GPUACCELERATED=1 GPU_COMPUTE_CAPABILITY=70 EXE=myapp SOURCES='<name>'
> ```
> 
> where is a space-separated list of your source files (without file extensions).
> 
> If successful, this will make a `myapp` executable. Does this work?

I try again, but still have some problem like last photo I post. 

I will run this in my the other machine which can run normally.

I really appreciate your help!
