### ISSUE TITLE
How can I debug the quest code in ubuntu?

### ISSUE THREAD

**Issue by amandalqy** [QuEST-Kit/QuEST#248]
Hi! Is there any debugging tool that is convenient for debugging the quest code in ubuntu?

**Comment by TysonRayJones** [comment]
Hi Amanda,

You can use any C debugger in Ubuntu, and there are some [API functions](https://quest-kit.github.io/QuEST/group__debug.html) to help with troubleshooting.

**Comment by amandalqy** [comment]
Thanks a lot!
