### ISSUE TITLE
Running distributed and on GPUs

### ISSUE THREAD

**Issue by al-rigazzi** [QuEST-Kit/QuEST#251]
Hello,

are there technical reasons which make it impossible to run QuEST distributed AND on GPUs?

**Comment by TysonRayJones** [comment]
Hi Al,
While not impossible, it hasn't proved worthwhile ([here](https://github.com/QuEST-Kit/QuEST/issues/220) are some previous comments on this)

**Comment by al-rigazzi** [comment]
Thanks @TysonRayJones and sorry for not seeing the other issue! I’m offline these days, but I’ll add some comments soon!

**Comment by TysonRayJones** [comment]
No problem, it's hard to notice things in closed issues. I'll keep this issue open in case you want to pen further thoughts
