### ISSUE TITLE
Incorrect ordering of states

### ISSUE THREAD

**Issue by Bebotron** [QuEST-Kit/QuEST#252]
Per the documentation (https://quest-kit.github.io/QuEST/group__init.html#ga0379e21efca0767a22607fc0e26a5a22),  the ordering of states should be (for a 3 qubit system in this example) 0 = |000>, 1 = |001>, 2 = |010>, 3 = |011>, ..., 7 = |111>, as is conventional in QI. But the following code
```C++
#include <iostream>
#include <QuEST.h>

using namespace std;

int main() {
    QuESTEnv env = createQuESTEnv();
    Qureg psi = createQureg(3, env);
    for(int i = 0; i < 8; i++) {
        initClassicalState(psi, i);
        cout << "|";
        for(int i = 0; i < 3; i++)
            cout << measure(psi, i);
        cout << ">" << endl;
    }
    return 0;
}
```
Produces the output
```
|000>
|100>
|010>
|110>
|001>
|101>
|011>
|111>
```
Which is the completely wrong ordering. I guess the documentation should be fixed to accurately reflect this ordering, but I think a more appropriate change would be to fix the code to be consistent with the documentation and convention.

**Comment by TysonRayJones** [comment]
Hi David,

The ordering is consistent with the doc and the QI convention; you've just made a small mistake in your code.
Qubits, like their classical bit counterparts, are indexed _from the right_. That is, the _first_ bit of sequence `011` is `1`, or the least significant. 

You write
```C++
        for(int i = 0; i < 3; i++)
            cout << measure(psi, i);
```
and are iterating the bits right-to-left, but you print them left-to-right using `<<`.

To print the bits left-to-right (most to least significant) in the correct order, you need to reverse your loop to:
```C++
        for(int i = 2; i <=0; i--)
            cout << measure(psi, i);
```
Hope this helps!

**Comment by Bebotron** [comment]
Thanks that sure clarifies this really well! I guess I was used to the undefined ordering in some Nielsen and Chuang problems, but evidently this is the way qubits are ordered in QI. Thanks!
