### ISSUE TITLE
cannot use "multiRotatePauli()"

### ISSUE THREAD

**Issue by zhijietang0710** [QuEST-Kit/QuEST#253]
Hi, 

I tried to use "multiRotatePauli()" function in c++, but it gave an error message:  **_error: no matching function for call to       'multiRotatePauli'
  multiRotatePauli(qubits, (int[]) {0,1}, (int[]) {2,3}, 2, .1)
 note: candidate function not viable: no known conversion from 'int [2]' to 'enum pauliOpType *' for 3rd argument
void multiRotatePauli(Qureg qureg, int* targetQubits, enum pauliOpType* targetPaulis, int nu..._**. do anyone know how to use this function?

**Comment by Bebotron** [comment]
Try defining the arguments separately:
```C++
int targets[2] = {0,1};
pauliOpType paulis[2] = {PAULI_Y, PAULI_Z};
multiRotatePauli(qubits, targets, paulis, 2, 0.1);
```
I've struggles getting the enumerated paulis working, but the above works for me.

**Comment by TysonRayJones** [comment]
Hi all,

A one-liner is possible, without any warnings.
In `C99`:
```C
multiRotatePauli(qureg, (int[]) {0,1}, (enum pauliOpType []) {2,3}, 2, .1);
```

In`C++11`, you'll need to use the enums:
```C++
multiRotatePauli(qureg, (int[]) {0,1}, (enum pauliOpType []) {PAULI_Y,PAULI_Z}, 2, .1);
```

I'm kicking myself for not aliasing `pauliOpType`. It was originally an internal type which only appeared later in the API since it was quick & easy. Ho hum!
