### ISSUE TITLE
Use -std=c++11

### ISSUE THREAD

**Issue by Bebotron** [QuEST-Kit/QuEST#254]
I'm trying to use C++11, so naively I thought it could work if I changed to `-std=c++11` in line 221 of `QuEST/QuEST/CMakeLists.txt`
```
# ----- C++ COMPILER FLAGS --------------------------------------------------

# set C++ flags that are common between compilers and build types
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} \
    -std=c++98 -Wall"
)
```
But I still get the error
```
C:/PROGRA~2/MINGW-~1/I686-5~1.0-P/mingw32/i686-w64-mingw32/include/c++/bits/c++0x_warning.h:32:2: error: #error 
This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must 
be enabled with the -std=c++11 or -std=gnu++11 compiler options. 
```
I think this should be a simple fix, but I'm just not too familiar with CMake so I don't know how to specify the appropriate flag. So any help on how to set (if it plays nice with QuEST) `-std=c++11` for the compilation would be great!

**Edit:**
I got `#include <random>` to work in `QuEST/tests/main.cpp` without any errors and compiling `cmake .. -G "MinGW" -DTESTING=ON`. But when I try to use my own source file `QuEST/build/main.cpp` and compile `cmake .. -G "MinGW" -DUSER_SOURCE="main.cpp"`, I get the same above error.

**Comment by TysonRayJones** [comment]
Hi David,

I'm no CMake expert myself, but I did setup CMake for the unit testing to use C++14 (see [CMakeLists.txt](https://github.com/QuEST-Kit/QuEST/blob/master/tests/CMakeLists.txt))

I did so via
```cmake
set_property(TARGET tests PROPERTY CXX_STANDARD 14)
```

Btw, I have to apologise for ever recommending MinGW to compile QuEST on Windows. I've since made a derivative project ([QuESTlink](https://github.com/QTechTheory/QuESTLink)) MSVC compatible directly, which I'll eventually do also for QuEST.

**Comment by Bebotron** [comment]
Thanks for the reference that definitely helped! It was a bit finicky but I got this working by compiling QuEST first following you comment https://github.com/QuEST-Kit/QuEST/issues/181#issuecomment-572414741, and then adding 
```CMake
set_property(TARGET scratch PROPERTY CXX_STANDARD 11)
```
to my CMake script, and compiling that again with `mingw32-make`. Apparently my default `make` alias used GNU Make 3.81, while `mingw32-make` uses GNU Make 4.1. I'm not fully understanding exactly how that changes things but the former gave me errors and the latter did not. So I'll leave it at that and compile like https://github.com/QuEST-Kit/QuEST/issues/181#issuecomment-572414741 from now on and close the issue. Thanks for the help!
