### ISSUE TITLE
Can i use another structure？like tree

### ISSUE THREAD

**Issue by onmywayto-professional** [QuEST-Kit/QuEST#266]
Is it too wasteful to use arrays to store quantum superposition states? Can I store them in a tree structure?
Since there is only one target bit for each operation, can I operate on only one qubit at a time and add another all qubits in the final measurement?

**Comment by TysonRayJones** [comment]
Hi there,
That's an interesting question about simulation of quantum circuits (QC) in general, but QuEST specifically uses "full state" or "brute force" simulation. There are many _many_ methods of QC simulation in the literature, with different runtime and memory trade-offs and optimality for different families of circuits. I'm unsure, but it sounds like you're describing simulation via [tensor network contraction](https://epubs.siam.org/doi/abs/10.1137/050644756).
This is off-topic for QuEST, so I'll close this issue, but I hope the link helps!
