### ISSUE TITLE
Is there false sharing？

### ISSUE THREAD

**Issue by onlyXR** [QuEST-Kit/QuEST#267]

**Comment by onmywayto-professional** [comment]
The sentence above”indexUp calculated by several adjacent iterations may exist in the same cache line“，I mean the array subscript is indexUp

Besides, I have some questions
I used the intel advisor tool to analyze and found that 40% of the time is spent on memory reading and writing. Is there any way to solve this problem?
I would be very grateful if you can answer the questions in your busy schedule.
Thanks
