### ISSUE TITLE
MPI is used, but the speed gets slower

### ISSUE THREAD

**Issue by xiaozhuzhu2333** [QuEST-Kit/QuEST#268]
QuEST-2.1.0
the num of qbits is 30
I use openMP and MPI but the result is confused

use  $ ./demo
the running time is 600s

but use $ mpirun -np 4 ./demo
the running time is 6000s

**Comment by TysonRayJones** [comment]
Hi there,

QuEST _hybridises_ distribution and multithreading. You should _only_ use multithreading when running on a single machine. Distribution requires using more memory (for communication) and additional steps for exchanging memory between machines over a network, and should not be used to parallelise simulation locally.

Hope this helps!
