### ISSUE TITLE
Implementing Grover's Algortihm

### ISSUE THREAD

**Issue by sky-16** [QuEST-Kit/QuEST#275]
I am new in the field of QC Simulators and found Quest to be interesting. Can somebody guide me on how to implement Grover's Algorithm on Quest.

**Comment by TysonRayJones** [comment]
Hi there,
I've added an example of Grover's search [here](https://github.com/QuEST-Kit/QuEST/blob/more_examples/examples/grovers_search.c). All questions and feedback welcome! I hope to add several more examples before releasing QuEST v3.3.0 within the week.
