### ISSUE TITLE
Braket with a state in computational basis

### ISSUE THREAD

**Issue by Milos9304** [QuEST-Kit/QuEST#284]
One might be interested to calculate ``<φ|θ>`` where φ is a state in computational basis and θ a qureg. For example, such calculation can be done to calculate an overlap of the resulting state θ  of a quantum algorithm with the correct solution φ we know apriori.

Hence I propose to implement a ``calcInnerProductWithClassicalState(int classical_descriptor, Qureg qureg)`` that does not need to allocate additional 2^n amplitudes compared to ``initClassicalState(qureg_classical, 0b11001);calcInnerProduct(qureg_classical, qureg)``. What do you think?

**Comment by TysonRayJones** [comment]
You might kick yourself :) If I understand right, you're describing fetching a single amplitude (definitionally). 

Let our state-vector be:
![image](https://user-images.githubusercontent.com/29574749/124804055-c6778a00-df51-11eb-8863-5ab98c1a914a.png)

Then the inner product with computational basis *i* is...
![image](https://user-images.githubusercontent.com/29574749/124803928-9d56f980-df51-11eb-974b-661915f93ac5.png)
the *i*-th amplitude. 
Hence you can use the existing [`getAmp`](https://quest-kit.github.io/QuEST-develop-doc/group__calc.html#ga30d6f8b7c766c9c9914b2c61a2fc0def) function.

Similarly, for density matrix
![image](https://user-images.githubusercontent.com/29574749/124804327-13f3f700-df52-11eb-8c9a-0868de58266e.png)
the density matrix inner product is
![image](https://user-images.githubusercontent.com/29574749/124805316-418d7000-df53-11eb-9ebe-ce074a9e6480.png)
which you can obtain with the existing [`getDensityAmp`](https://quest-kit.github.io/QuEST-develop-doc/group__calc.html#gadca286c4ad5cde6124d4e80a7ab95a68) function.

Note this isn't a coincidental algebraic result; it is the very definition of our classical state amplitudes:
![image](https://user-images.githubusercontent.com/29574749/124806046-2838f380-df54-11eb-836f-d7f8eee926e0.png)
where *j* form an orthonormal basis.
