### ISSUE TITLE
Can Quest run on Apple M1 ? 

### ISSUE THREAD

**Issue by keithyau** [QuEST-Kit/QuEST#301]
Wondering if llvm / Clang can be supported Apple M1

**Comment by TysonRayJones** [comment]
Hi there,

I don't have an M1 handy to test, but certainly there's nothing special in the QuEST architecture to preclude it.
I would confidently assume that serial QuEST is supported by whatever the M1 compiling chain is.

For multithreading; QuEST supports OpenMP versions 2.0 (in [develop](https://github.com/QuEST-Kit/QuEST/tree/develop) - the master branch temporarily requires 3.1) through to OpenMP 5.0 (the latest). It is not yet tested with 5.1, but is expected compatible. Mature releases of Clang support OpenMP (e.g. OpenMP 4.5 in Clang 13). If the M1 compiling chain fully supports clang, then I expect QuEST to compile fine. 

But one never knows until they test!

**Comment by keithyau** [comment]
thank you !

**Comment by mmoelle1** [comment]
Hi there,

I tried compiling QuEST on an M1 and it works. However, it needs some modification of the `CMakeLists.txt` file.

Original (same for C++ compiler):
```
# TODO standardize
# set C compiler flags based on compiler type
if ("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang")
  # using Clang
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} \
    -mavx -Wall"
  )
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
  # using GCC
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} \
    -mavx -Wall"
  )
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "Intel")
  # using Intel
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} \
    -fprotect-parens -Wall -xAVX -axCORE-AVX2 -diag-disable cpu-dispatch"
  )
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
  # using Visual Studio
  string(REGEX REPLACE "/W3" "" CMAKE_C_FLAGS ${CMAKE_C_FLAGS})
  string(REGEX REPLACE "-W3" "" CMAKE_C_FLAGS ${CMAKE_C_FLAGS})
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} \
    -w"
  )
endif()
```

Apple's default compiler reports itself as `AppleClang` so by accident no `-mavx` flag is set which does not work on M1. However, when you install a true GCC (e.g. using homebrew), the about detects a `GNU` compiler and sets `-mavx` which leads to a compiler error. The same problem happens on any non-x86_64 architecture (ARM/ARM64, PPC). 

As a quick fix I'd suggest to wrap the entire `if()...endif()` block in `if (CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(amd64)|(AMD64)") ... endif()` which will disable it for any non-x86_64 architecture.

**Comment by TysonRayJones** [comment]
Hi Matthias,
That's really useful to know, thanks very much! 
I've been meaning to test whether QuEST can meaningfully utilise auto-vectorisation for a while, so I'll add that to my backlog and update the build afterward (or remove the flag entirely). @rrmeister who has a better understanding of the CMake build may also be interested.
Thanks again!

**Comment by ekapit** [comment]
I just got a new M1 Max laptop, and am trying out QuEST on it. Naively, it should be extremely fast-- this CPU has 10 cores and 200+ GB/s usable memory bandwidth, higher than most Xeons, and since that's the primary bottleneck it should be very quick. And I was able to get Apple clang to link to openMP correctly, so it is multithreaded. However when trying it out it ends up being _much_ slower than on intel chips. I tried setting "march=apple-m1" as a compiler flag to make sure it's compiling native code but that didn't seem to change anything. I strongly suspect this is a compiler issue, though I'm not sure what to try next.

Has anyone gotten QuEST to perform well on Apple Silicon?

**Comment by mmoelle1** [comment]
Hi Tyson,

I tried you code on my Apple M1 (MacBook Pro) not the M1 Max or Pro as the OP.

```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
```

Serial
```
❯ clang github_issue.c -O3 -o test
8.559273 (s)
```

OpenMP
```
❯ clang github_issue.c -O3 -openmp -o test
7.743996 (s) OMP_NUM_THREADS=1
4.227490 (s) OMP_NUM_THREADS=2
4.195969 (s) OMP_NUM_THREADS=4
4.211792 (s) OMP_NUM_THREADS=8
```

GCC 11.2.0.3 (from home-brew)

Serial
```
7.596629 (s)
```

OpenMP
```
7.835089 (s) OMP_NUM_THREADS=1
5.348674 (s) OMP_NUM_THREADS=2
5.083343 (s) OMP_NUM_THREADS=4
5.096947 (s) OMP_NUM_THREADS=8
```

For GCC the line `private  (i,j,j0k,j1k,a1,a2)` needs to be removed.

**Comment by TysonRayJones** [comment]
Thanks very much Matthias! (and oops regarding GCC; I forgot we have to pre-declare our OpenMP variables there like filthy animals).

Those are encouraging times, which to me confirm ekapit's performance issues are indeed related to build parameters, as we discussed above. Or maybe we're comparing to some very impressive Intel chips! :)

**Comment by fieldofnodes** [comment]
Hi, I have an M1 Max macbook pro and I just added #346 to this as I can not get QuEST to make for testing.

**Comment by TysonRayJones** [comment]
Confirming QuEST v4 (due for release mid-September) runs fine on an M1 Mac (which is now my main development machine!), with a [naive build](https://github.com/QuEST-Kit/QuEST/blob/v4/scripts/compile.sh). We'll make sure our revised CMake build avoids the above issues.
