### ISSUE TITLE
New Feature: Calculating partial trace for density matrix

### ISSUE THREAD

**Issue by AjinkyaGawali** [QuEST-Kit/QuEST#312]
Currently there is no way to get a reduced density matrix representation of a density matrix, But a method that would calculate partial trace or Einstein summation of a matrix on target qubits could make that possible.

**Comment by TysonRayJones** [comment]
Relevant algorithm: https://arxiv.org/abs/1601.07458

**Comment by TysonRayJones** [comment]
Subsequent algorithm: https://arxiv.org/pdf/1709.06346.pdf

**Comment by TysonRayJones** [comment]
A long overdue update: I devise a partial trace algorithm compatible with QuEST's distribution model in [https://arxiv.org/abs/2311.01512](https://arxiv.org/abs/2311.01512), in Sec V. H. (pg 45). An example implementation is [here](https://github.com/TysonRayJones/Distributed-Full-State-Algorithms/blob/f29bd6b81156bd315d414cd43f94602be9e00617/src/distributed_densitymatrix.hpp#L347). This will be added as a QuEST function in the upcoming v4 release.

**Comment by TysonRayJones** [comment]
added in c230706
