### ISSUE TITLE
New feature: QASM outputter and parser

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#33]
Possible now that gates have a central, hardware-agnostic place in QuEST_ops.h

**Comment by TysonRayJones** [comment]
QASM generator added in a develop branch

**Comment by TysonRayJones** [comment]
QASM parser: just use GNU Bison to build a C parser from QASM CFG?

**Comment by oerc0122** [comment]
Currently developing this with some extensions to OpenQASM.
