### ISSUE TITLE
Optimise multi-controlled gates

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#332]
They can leverage the follow two optimisations for _significant_ speedup:

- no branching nor superfluous memory access (to avoid needless cache misses)
- packing before communication (as is possible in the optimised SWAP gate, but simpler)

See distributed manuscript!

**Comment by ananthakrishnagopal** [comment]
Hi,
Is there any progress on this? I am also interested in this. If possible would like to work on it.

**Comment by TysonRayJones** [comment]
Hi Ananthakrishna,

Coincidentally yes! The optimised version was recently outlined in [this manuscript](https://arxiv.org/abs/2311.01512), and implemented in [this repo](https://github.com/TysonRayJones/Distributed-Full-State-Algorithms) (see [this function](https://github.com/TysonRayJones/Distributed-Full-State-Algorithms/blob/fdc33ad7d13f058da8ac5a450c0fcf7f7f6ffa94/src/distributed_statevector.hpp#L81)). All algorithms of that manuscript are presently being integrated into QuEST, simultaneously with a refactor of QuEST's backend, and expected completed in the next 2 weeks (fingers crossed).

Given that the algorithm's code is already written, but the surrounding software arch is _not_, there's not realy much possibility of external help, but thanks enormously for the kind enthusiasm!

**Comment by ananthakrishnagopal** [comment]
Hi Tyson,

Many thanks for your mail. Looking forward to the updates to QuEST. If
there's any other future work that you're planning, would love to
contribute.

Thanks and all the best!

**Comment by TysonRayJones** [comment]
Done in 942d3ca (for expected v4 release mid-Sep)
