### ISSUE TITLE
Catch Header file outdated 

### ISSUE THREAD

**Issue by exAClior** [QuEST-Kit/QuEST#337]
# Description
Compiling fails with error like `error: call to non-‘constexpr’ function ‘long int sysconf(int)’`
# Reason 
As per https://github.com/OpenImageDenoise/oidn/issues/106#issue-848660709, catch2 header file is outdated for newer version of glibc. 
# Solution
Replace tests/catch/catch.hpp with newer version on Catch2 repo.

**Comment by TysonRayJones** [comment]
Since we have modified the catch header to support distributed unit testing, this potentially isn't so simple a fix. I'll investigate!

**Comment by rrmeister** [comment]
#348 potentially fixes this, it updates Catch2 to the latest v2.x availabe. @exAClior can you confirm compiling works as expected in your setup now?

**Comment by exAClior** [comment]
@rrmeister Hi, sorry for the delay. I can confirm compiling works. I also tried all the tests, they work too with that branch. I am using AMD platform.
