### ISSUE TITLE
Is gcc required to be a specific version

### ISSUE THREAD

**Issue by fieldofnodes** [QuEST-Kit/QuEST#342]
## Versions of gcc
I am running the following on my machine
```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Does this pose an issue for running QuEST?

**Comment by rrmeister** [comment]
Hi Jonathan,

QuEST should compile fine on a wide range of compilers, but we do not explicitly test every possible version of every compiler. If you want to make sure everything works properly, you can run the test suite as described in the documentation.

Hope it helps,
Cheers!
