### ISSUE TITLE
Conflict between MPI and previous installation of anaconda on Ubuntu

### ISSUE THREAD

**Issue by fieldofnodes** [QuEST-Kit/QuEST#343]
When I run: sudo apt-get install openmpi-bin libopenmpi-dev I get the following:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenmpi-dev is already the newest version (4.0.3-0ubuntu1).
openmpi-bin is already the newest version (4.0.3-0ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.

But when I run: mpicc --version I get the following error:

$HOME/anaconda3/bin/mpicc: line 285: x86_64-conda_cos6-linux-gnu-cc: command not found

I have anaconda running on my machine, but this seems like a weird output.

Thoughts?

**Comment by ChienKaiMa** [comment]
From [https://github.com/RcppCore/Rcpp/issues/770](https://github.com/RcppCore/Rcpp/issues/770), `conda install gxx_linux-64` or something similar should do the work.
What does it have to do with QuEST? Please provide more details if you face installation problems.

**Comment by fieldofnodes** [comment]
That did the trick.

Perfect thanks.

I did not know what it had to do with QuEST, it occurred when I was installing the MPI on the QuEST downloads page.

Problem solved with 

> From [RcppCore/Rcpp#770](https://github.com/RcppCore/Rcpp/issues/770), `conda install gxx_linux-64` or something similar should do the work. What does it have to do with QuEST? Please provide more details if you face installation problems.
