### ISSUE TITLE
Would it be possible to run QuEST with AMD GPUs?

### ISSUE THREAD

**Issue by HandyKurniawan** [QuEST-Kit/QuEST#356]
I would like to use QuEST simulator in my university HPC. Unfortunately, we only have the AMD GPUs, would it be possible to compile and run with it?

Thanks :)

**Comment by TysonRayJones** [comment]
Thanks to the work of [Bruno](https://github.com/bvillasen), yes! AMD GPU support (through [HIP](https://github.com/ROCm-Developer-Tools/HIP)) is currently on the [develop](https://github.com/QuEST-Kit/QuEST/tree/develop) branch, and will be available in the main branch at the next release (intendedly soon)!

**Comment by HandyKurniawan** [comment]
Thanks Tyson! Will wait for the next release then! 

Because I am installing QuEST through Spack and it can only get from the released version.

**Comment by TysonRayJones** [comment]
Ahh I understand - then good news, QuEST [v3.6.0](https://github.com/QuEST-Kit/QuEST/releases/tag/v3.6.0) is out! :)
