### ISSUE TITLE
New feature, testing: Test MT twister seeding

### ISSUE THREAD

**Issue by aniabrown** [QuEST-Kit/QuEST#7]
- Is there a way to unit test this? 
- Do the current methods to get time, pid and hostname in QuESTSeedRandomDefault fail on any architectures or OS?

**Comment by TysonRayJones** [comment]
v4's RNG (https://github.com/QuEST-Kit/QuEST/commit/4163622fbc9b3f020f55cd7afcbd43c522c7ad4d) uses C++'s standard-library interface to MT, with default seeds sampled using `std::random_device`, which attempts to use machine's cryptographically secure RNG if available. Will test RNG via the API functions which use it (measurement and random state initialisation)
